version: '3.1'

# Redmine with MySQL
services:
  mysql:
    image: ec2k-redmine/mysql
    container_name: mysql
    restart: always
    env_file:
      - ./mysql-settings.env
    volumes:
      - main-redmine-db:/var/lib/mysql

  redmine:
    image: ec2k-redmine/redmine
    container_name: redmine
    restart: always
    ports:
      - 51680:3000
    links:
      - mysql
    env_file:
      - ./redmine-db-settings.env
    volumes:
      - main-redmine-files:/usr/src/redmine/files

volumes:
  main-redmine-db:
    external: true
  main-redmine-files:
    external: true
